name: Build Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

permissions:
  contents: read  # Ensure read access to the repository's content

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      # Step 3: Install dependencies for `uv`
      - name: Install `uv` and project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv  # Install the `uv` tool (if hosted on PyPI)
          uv sync          # Sync dependencies using `uv`

      # Step 4: Build the project
      - name: Build the project
        run: |
          uv build          # Run the `uv build` command to build the project

      # Optional: Verify the build
      - name: Verify build
        run: |
          echo "Build completed successfully!"